#!/usr/bin/env bash
# Remove generated files, so the tree is back to what git tracks.
#
# Everything this touches is regenerated by a script in this directory, and
# nothing it touches is checked in -- .gitignore lists the same set. Prefer this
# over `build.sh -p` when you just want the tree clean without kicking off a
# rebuild.
#
# Two tiers, because the costs of regenerating differ by an order of magnitude:
#
#   default  the apps' out-of-tree build dirs. The thing you actually want gone
#            after a devicetree or Kconfig edit, and a couple of minutes to
#            rebuild.
#   --all    + everything else generated: twister's output, the editor's merged
#            compile database and the clangd index caches beside it, the host
#            harness's generated protobuf code and bytecode cache, and stray
#            console captures.
#
# host/.venv survives both tiers. It is gitignored like the rest, but it is
# created by hand (host/README.md) rather than by a script here, and refilling it
# needs the network.
#
# The app list is spelled out rather than globbed, and -a is checked against it,
# so this can only ever delete a build dir belonging to an app this repo has.
#
# Usage:
#   scripts/cleanup.sh                  # every app's build dir
#   scripts/cleanup.sh -a peer-node     # just that one
#   scripts/cleanup.sh --all            # every generated file in the repo
#   scripts/cleanup.sh --all -n         # print what would go, delete nothing
set -euo pipefail
shopt -s nullglob

APPS=(gateway peer-node)

# Repo root = parent of this script's dir, resolved regardless of where it's called from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
	cat <<'USAGE'
Usage: scripts/cleanup.sh [-a <app>] [--all] [-n]

  -a <app>   limit to one app's build dir (gateway or peer-node)
  --all      also remove twister-out/, the editor index and clangd caches,
             host/ generated protobuf code and __pycache__, console*.txt
  -n         dry run: print what would be removed
USAGE
}

ALL=0
DRY=0
SCOPED=""

while [[ $# -gt 0 ]]; do
	case "$1" in
	-a)
		if [[ $# -lt 2 ]]; then
			echo "-a needs an app name (${APPS[*]})." >&2
			exit 2
		fi
		SCOPED="$2"
		shift 2
		;;
	--all)
		ALL=1
		shift
		;;
	-n | --dry-run)
		DRY=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		# Unknown flags are an error rather than something to ignore: silently
		# skipping one would turn a typo'd narrow clean into a full one.
		echo "unknown argument '$1'." >&2
		usage >&2
		exit 2
		;;
	esac
done

if [[ -n "$SCOPED" ]]; then
	known=0
	for app in "${APPS[@]}"; do
		if [[ "$app" == "$SCOPED" ]]; then
			known=1
		fi
	done
	if [[ "$known" -eq 0 ]]; then
		echo "unknown app '$SCOPED' (${APPS[*]})." >&2
		exit 2
	fi
	if [[ "$ALL" -eq 1 ]]; then
		echo "--all is repo-wide, so it cannot be scoped with -a." >&2
		exit 2
	fi
	APPS=("$SCOPED")
fi

removed=0
freed_kb=0

# drop <path> -- remove it if it exists, and tally what that frees.
drop() {
	local path="$1"
	[[ -e "$path" ]] || return 0

	# Every path below is built from $REPO, but check rather than trust: an
	# `rm -rf` that escaped the repo would be silent and unrecoverable.
	case "$path" in
	"$REPO"/?*) ;;
	*)
		echo "refusing to remove '$path': outside $REPO" >&2
		exit 3
		;;
	esac

	local kb
	kb="$(du -sk "$path" | awk '{print $1}')"
	freed_kb=$((freed_kb + kb))
	removed=$((removed + 1))

	if [[ "$DRY" -eq 1 ]]; then
		echo "Would remove ${path#"$REPO"/}"
	else
		rm -rf "$path"
		echo "Removed ${path#"$REPO"/}"
	fi
}

for app in "${APPS[@]}"; do
	drop "$REPO/$app/build"
done

if [[ "$ALL" -eq 1 ]]; then
	# Twister's output. Never stale -- test.sh passes --clobber-output, so every
	# run rebuilds it from scratch -- but each suite is a complete Zephyr image,
	# which makes this by far the largest thing in the tree. The numbered dirs
	# are twister's own rotation, left by any run that dropped that flag.
	drop "$REPO/twister-out"
	for dir in "$REPO"/twister-out.*/; do
		drop "${dir%/}"
	done

	# Editor index: the merged compile database (scripts/ide-index.sh) and the
	# clangd index caches beside it. Both are per-machine and full of absolute
	# paths; nothing in the build reads either.
	drop "$REPO/compile_commands.json"
	drop "$REPO/.cache"
	for app in "${APPS[@]}"; do
		drop "$REPO/$app/.cache"
	done

	# Host harness: the protobuf code generated from proto/node.proto by
	# host/generate.sh, plus CPython's bytecode cache.
	drop "$REPO/host/node_pb2.py"
	for stub in "$REPO"/host/*_pb2.pyi; do
		drop "$stub"
	done
	while IFS= read -r -d '' cache; do
		drop "$cache"
	done < <(find "$REPO/host" -type d -name __pycache__ -prune -print0)

	# Serial console captures (scripts/console.sh), which land at the repo root.
	for capture in "$REPO"/console*.txt; do
		drop "$capture"
	done
fi

if [[ "$removed" -eq 0 ]]; then
	if [[ "$ALL" -eq 1 ]]; then
		echo "Nothing to clean — the repo holds no generated files."
	else
		echo "Nothing to clean — no build dir exists for: ${APPS[*]}"
	fi
	exit 0
fi

human="$(awk -v kb="$freed_kb" 'BEGIN { if (kb >= 1024) printf "%.1f MB", kb / 1024; else printf "%d KB", kb }')"
if [[ "$DRY" -eq 1 ]]; then
	echo "Would free $human across $removed path(s)."
else
	echo "Freed $human across $removed path(s)."
fi
