#!/usr/bin/env bash
# Remove build artifacts from firmware/build so the next build starts clean.
#
# This deletes the whole out-of-tree build dir (safe to nuke: it's fully
# regenerated by scripts/build.sh). Prefer this over `build.sh -p` when you
# just want the tree clean without kicking off a rebuild.
#
# Usage:
#   scripts/cleanup.sh            # remove firmware/build
set -euo pipefail

# Repo root = parent of this script's dir, resolved regardless of where it's called from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$REPO/firmware/build"

if [[ ! -d "$BUILD_DIR" ]]; then
	echo "Nothing to clean — $BUILD_DIR does not exist."
	exit 0
fi

rm -rf "$BUILD_DIR"
echo "Removed $BUILD_DIR"
