#!/usr/bin/env bash
# Remove build artifacts from the apps' build dirs so the next build starts clean.
#
# This deletes whole out-of-tree build dirs (safe to nuke: they're fully
# regenerated by scripts/build.sh). Prefer this over `build.sh -p` when you just
# want the tree clean without kicking off a rebuild.
#
# The app list is spelled out rather than globbed, so this can only ever delete a
# build dir belonging to an app this repo actually has.
#
# twister-out/ is deliberately left alone: scripts/test.sh passes
# --clobber-output, so the test tree is already rebuilt from scratch every run.
#
# Usage:
#   scripts/cleanup.sh                 # remove every app's build dir
#   scripts/cleanup.sh -a peer-node  # remove just that one
set -euo pipefail

APPS=(gateway peer-node)

# Repo root = parent of this script's dir, resolved regardless of where it's called from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ "${1:-}" == "-a" ]]; then
	if [[ $# -lt 2 ]]; then
		echo "-a needs an app name (${APPS[*]})." >&2
		exit 2
	fi
	APPS=("$2")
fi

removed=0
for app in "${APPS[@]}"; do
	build_dir="$REPO/$app/build"
	if [[ -d "$build_dir" ]]; then
		rm -rf "$build_dir"
		echo "Removed $build_dir"
		removed=$((removed + 1))
	fi
done

if [[ "$removed" -eq 0 ]]; then
	echo "Nothing to clean — no build dir exists for: ${APPS[*]}"
fi
